
# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

# language: objective-c
# osx_image: xcode8.2
# before_install: 
# - carthage bootstrap --verbose
# script:
# - set -o pipefail && xcodebuild -project MastodonKit.xcodeproj -scheme "MastodonKitTests_iOS" test -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 7" | xcpretty
# - set -o pipefail && xcodebuild -project MastodonKit.xcodeproj -scheme "MastodonKitTests_macOS" test -sdk macosx -destination "platform=macOS" | xcpretty
# - pod lib lint --quick --allow-warnings


language: objective-c
cache: cocoapods
osx_image: xcode7.3
sudo: false
xcode_project: MastodonKit.xcodeproj
xcode_scheme: MastodonKit
env:
  global:
    - IOS_SDK=iphonesimulator9.3
    - IOS_SCHEME="MastodonKit-iOS"
    - MACOS_SDK=macosx10.11
    - MACOS_SCHEME="MastodonKit-macOS"
  matrix:
    - DESTINATION="OS=9.2,name=iPad 2"         SDK="$IOS_SDK"   SCHEME="$IOS_SCHEME"
    - DESTINATION="OS=9.2,name=iPad Air"       SDK="$IOS_SDK"   SCHEME="$IOS_SCHEME"
    - DESTINATION="OS=9.2,name=iPhone 5"       SDK="$IOS_SDK"   SCHEME="$IOS_SCHEME"
    - DESTINATION="OS=9.2,name=iPhone 6s"      SDK="$IOS_SDK"   SCHEME="$IOS_SCHEME"
    - DESTINATION="OS=9.3,name=iPhone 6s"      SDK="$IOS_SDK"   SCHEME="$IOS_SCHEME"
    - DESTINATION="OS=8.4,name=iPhone 6"       SDK="$IOS_SDK"   SCHEME="$IOS_SCHEME"
    - DESTINATION="OS=8.4,name=iPad Air"       SDK="$IOS_SDK"   SCHEME="$IOS_SCHEME"
    - DESTINATION="OS=9.1,name=Apple TV 1080p" SDK="$TVOS_SDK"  SCHEME="$TVOS_SCHEME"
    - DESTINATION="OS=9.2,name=Apple TV 1080p" SDK="$TVOS_SDK"  SCHEME="$TVOS_SCHEME"
    - DESTINATION="platform=OS X,arch=x86_64"  SDK="$MACOS_SDK" SCHEME="$MACOS_SCHEME"
before_install:
  - brew update
  - if brew list | grep -q carthage; then
      echo Carthage installed. Proceed without installing;
      carthage version;
    else
      echo Carthage not installed. Installing using homebrew;
      brew install carthage;
    fi
install:
  - carthage bootstrap --verbose
script:
  - set -o pipefail
  - xcodebuild -version
  - if [ "$SCHEME" == "MastodonKit-macOS" ]; then
      xcodebuild -project MastodonKit.xcodeproj -scheme "$SCHEME" -destination "$DESTINATION" -sdk "$SDK" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO test -enableCodeCoverage YES | xcpretty -tc;
    else
      xcodebuild -project MastodonKit.xcodeproj -scheme "$SCHEME" -destination "$DESTINATION" -sdk "$SDK" test -enableCodeCoverage YES | xcpretty -tc;
    fi
after_success:
  - sleep 5