
# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode8.2
before_install: 
- brew update
- brew install carthage
- carthage bootstrap --verbose
script:
- set -o pipefail && xcodebuild -project MastodonKit.xcodeproj -scheme "MastodonKitTests_iOS" test -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 7" | xcpretty
- set -o pipefail && xcodebuild -project MastodonKit.xcodeproj -scheme "MastodonKitTests_macOS" test -sdk macosx -destination "platform=macOS" | xcpretty
- pod lib lint --quick --allow-warnings